<template>
  <router-view></router-view>
</template>

<script>

export default {
  provide: {
    availableBooks: [
      {
        bookTitle: "The Lord of the Rings",
        bookAuthor: "J.R.R Tolkien",
        bookISBN: "9788845292613",
        bookQuote: "Not all those who wander are lost",
        bookPublish: "29-07-1954",
        bookRate: "4.5",
        bookDescrip: "The future of civilization rests in the fate of the One Ring, which has been lost for centuries. Powerful forces are unrelenting in their search for it. But fate has placed it in the hands of a young Hobbit named Frodo Baggins, who inherits the Ring and steps into legend. A daunting task lies ahead for Frodo when he becomes the Ringbearer - to destroy the One Ring in the fires of Mount Doom where it was forged.\n",
        bookPic: "1",
      },
      {
        bookTitle: "The Little Prince",
        bookAuthor: "Antoine de Saint-Exupéry",
        bookISBN: "9780156012072",
        bookPublish: "06-04-1943",
        bookRate: "4.3",
        bookQuote: "Here is my secret. It is very simple: It is only with the heart that one can see rightly; what is essential is invisible to the eye",
        bookDescrip: "A pilot stranded in the desert awakes one morning to see, standing before him, the most extraordinary little fellow. \"Please,\" asks the stranger, \"draw me a sheep.\" And the pilot realizes that when life's events are too difficult to understand, there is no choice but to succumb to their mysteries. He pulls out pencil and paper... And thus begins this wise and enchanting fable that, in teaching the secret of what is really important in life, has changed forever the world for its readers.",
        bookPic: "2",
      },
      {
        bookTitle: "Turtles all the Way Down",
        bookAuthor: "John Green",
        bookISBN: "9780525555377",
        bookPublish: "10-10-2017",
        bookRate: "3.9",
        bookQuote: "You think you're the painter but you're the canvas",
        bookDescrip: "The story centers on 16-year-old Aza Holmes, an American high school student with OCD and anxiety, and her search for a fugitive billionaire who happens to be a neighbor's father. She is grieving the loss of her own father while a budding relationship grows between her and the billionaire's son. In his long-awaited return, John Green shares Aza's story with shattering, unflinching clarity. ",
        bookPic: "3",
      },      {
        bookTitle: "This is Going to Hurt: Secret Diaries of a Junior Doctor",
        bookAuthor: "Adam Kay",
        bookISBN: "9783442159703",
        bookPublish: "07-09-2017",
        bookRate: "4.4",
        bookQuote: "The depth of the lows is the price you pay for the height of the highs",
        bookDescrip: "This is Going to Hurt: Secret Diaries of a Junior Doctor is a collection of diary entries written by Kay during his medical training from 2004 to 2010. Kay's book discusses political issues in the health care system of the National Health Service in the United Kingdom and societal conflicts between the general population and neglected doctors.",
        bookPic: "4",
      },      {
        bookTitle: "Chaos: Making a New Science",
        bookAuthor: "James Gleick",
        bookISBN: "9780143113454",
        bookPublish: "29-10-1987",
        bookRate: "4.0",
        bookQuote: "Science was constructed against a lot of nonsense",
        bookDescrip: "Chaos introduces a whole new readership to chaos theory, one of the most significant waves of scientific knowledge in our time. From Edward Lorenz’s discovery of the Butterfly Effect, to Mitchell Feigenbaum’s calculation of a universal constant, to Benoit Mandelbrot’s concept of fractals, which created a new geometry of nature, Gleick’s engaging narrative focuses on the key figures whose genius converged to chart an innovative direction for science. In Chaos, Gleick makes the story of chaos theory not only fascinating but also accessible to beginners, and opens our eyes to a surprising new view of the universe.",
        bookPic: "5",
      },      {
        bookTitle: "Invisible Women: Exposing Data Bias in a World Designed for Men",
        bookAuthor: "Caroline Criado-Perez",
        bookISBN: "9781419729072",
        bookPublish: "07-03-2019",
        bookRate: "4.4",
        bookQuote: "There is no such thing as a woman who doesn't work. There is only a woman who isn't paid for her work",
        bookDescrip: "Data is fundamental to the modern world. From economic development, to healthcare, to education and public policy, we rely on numbers to allocate resources and make crucial decisions. But because so much data fails to take into account gender, because it treats men as the default and women as atypical, bias and discrimination are baked into our systems. And women pay tremendous costs for this bias, in time, money, and often with their lives.\n",
        bookPic: "6",
      },      {
        bookTitle: "The Universe in Your Hand: A Journey Through Space, Time",
        bookAuthor: "Christophe Galfard",
        bookISBN: "9781504684347",
        bookPublish: "27-08-2015",
        bookRate: "4.4",
        bookQuote: "Our image is here and will forever stay, and there is comfort in knowing that the memory of our lives will always be there, traveling among the stars",
        bookDescrip: "Imagine if The Hitchhiker's Guide to the Galaxy were a real handbook...Internationally renowned astrophysicist Christophe Galfard takes us on a wonder-filled journey through the past, present and future of the universe - a journey into science fact.",
        bookPic: "8",
      },      {
        bookTitle: "The Sixth Extinction: An Unnatural History",
        bookAuthor: "Elizabeth Kolbert",
        bookISBN: "9781498851210",
        bookPublish: "11-02-2014",
        bookRate: "4.1",
        bookQuote: "The current extinction has its own novel cause: not an asteroid or a massive volcanic eruption but 'one weedy species'",
        bookDescrip: "Over the last half-billion years, there have been five mass extinctions, when the diversity of life on earth suddenly and dramatically contracted. Scientists around the world are currently monitoring the sixth extinction, predicted to be the most devastating extinction event since the asteroid impact that wiped out the dinosaurs. This time around, the cataclysm is us. In The Sixth Extinction, Elizabeth Kolbert studies the relationship between human beings and the environment, and concludes that human behavior is on the verge of causing (or may have already caused) a mass-extinction—the sixth in the history of the planet.",
        bookPic: "9",
      },{
        bookTitle: "Alex's Adventures in Numberland",
        bookAuthor: "Alex Bellos",
        bookISBN: "9788806214999",
        bookPublish: "05-04-2010",
        bookRate: "4.1",
        bookQuote: "The thrill of mathes is the moment of instant revelation, from proofs such as this, when suddenly everything makes sense",
        bookDescrip: "Exploding the myth that maths is best left to the geeks, Alex Bellos covers subjects from adding to algebra, from set theory to statistics and from logarithms to logical paradoxes. In doing so, he explains how mathematical ideas underpin just about everything in our lives.",
        bookPic: "10",
      },{
        bookTitle: "AI Superpowers",
        bookAuthor: "Kai-Fu Lee",
        bookISBN: "9783854716913",
        bookPublish: "25-09-2018",
        bookRate: "4.1",
        bookQuote: "AI will do the analytical thinking, while humans will wrap that analysis in warmth and compassion",
        bookDescrip: "Dr. Kai-Fu Lee, one of the world's most respected experts on AI and China, reveals that China has suddenly caught up to the US at an astonishingly rapid and unexpected pace. AI Superpowers will help you understand what to expect of the effect that artificial intelligence will have on your future job opportunities by diving into where China and the US, the world's two leaders in AI, are heading with this breakthrough technology.",
        bookPic: "11",
      },{
        bookTitle: "The Man Who Mistook His Wife for a Hat",
        bookAuthor: "Oliver Wolf Sacks",
        bookISBN: "9780673976505",
        bookPublish: "26-12-1985",
        bookRate: "4.0",
        bookQuote: "You have to begin to lose your memory. If only in bits and pieces. To realize that memory is what makes our lives.",
        bookDescrip: "If a man has lost a leg or an eye, he knows he has lost a leg or an eye; but if he has lost a self—himself—he cannot know it, because he is no longer there to know it. Dr. Oliver Sacks recounts the stories of patients struggling to adapt to often bizarre worlds of neurological disorder. Here are people who can no longer recognize everyday objects or those they love; who are stricken with violent tics or shout involuntary obscenities; who have been dismissed as autistic or retarded, yet are gifted with uncanny artistic or mathematical talents. If inconceivably strange, these brilliant tales illuminate what it means to be human.",
        bookPic: "12",
      },{
        bookTitle: "Dune",
        bookAuthor: "Frank Herbert",
        bookISBN: "9780736692403",
        bookPublish: "10-08-1965",
        bookRate: "4.2",
        bookQuote: "I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fears. Where the fear has gone, there will be nothing, only I will remain.",
        bookDescrip: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for...",
        bookPic: "13",
      },{
        bookTitle: "Being Mortal: Medicine and What Matters in the End",
        bookAuthor: "Atul Gawande",
        bookISBN: "9780805095159",
        bookPublish: "07-11-2014",
        bookRate: "4.4",
        bookQuote: "The terror of sickness and old age is not merely the terror of the losses one is forced to endure but also the terror of the isolation.",
        bookDescrip: "Medicine has triumphed in modern times, transforming birth, injury, and infectious disease from harrowing to manageable. But in the inevitable condition of aging and death, the goals of medicine seem too frequently to run counter to the interest of the human spirit. Nursing homes, preoccupied with safety, pin patients into railed beds and wheelchairs. Hospitals isolate the dying, checking for vital signs long after the goals of cure have become moot. Doctors, committed to extending life, continue to carry out devastating procedures that in the end extend suffering.",
        bookPic: "14",
      },{
        bookTitle: "The Dip: A Little Book That Teaches You When to Quit",
        bookAuthor: "Seth Godin",
        bookISBN: "9781602528703",
        bookPublish: "10-05-2007",
        bookRate: "3.8",
        bookQuote: "Anything worth achieving in life has a dip.",
        bookDescrip: "The Dip: A Little Book That Teaches You When to Quit is the tenth published book by Seth Godin. It is a 76 page book that illustrates the concept of \"the dip\"—a temporary setback that can be overcome with persistence—and how to recognize if you are within one worth pushing through or one where you should quit.",
        bookPic: "15",
      },{
        bookTitle: "More Money Than God: Hedge Funds and the Making of a New Elite",
        bookAuthor: "Sebastian Mallaby",
        bookISBN: "9781408807347",
        bookPublish: "10-06-2010",
        bookRate: "4.1",
        bookQuote: "Hedge funds built their strategies on short selling, but governments imposed clumsy restrictions on shorting amid the post-Lehman panic.",
        bookDescrip: "Based on unprecedented access to the industry, More Money Than God provides the first authoritative history of hedge funds. This is the inside story of their origins in the 1960s and 1970s, their explosive battles with central banks in the 1980s and 1990s, and finally their role in the financial crisis of 2007-9.",
        bookPic: "19",
      },{
        bookTitle: "Hunger: A Memoir of (My) Body",
        bookAuthor: "Roxane Gay",
        bookISBN: "9780062420718",
        bookPublish: "13-06-2017",
        bookRate: "4.2",
        bookQuote: "I am trying to find ways to hold my head high when I walk into a room. And to stare right back when people stare at me.",
        bookDescrip: "In her phenomenally popular essays and long-running Tumblr blog, Roxane Gay has written with intimacy and sensitivity about food and body, using her own emotional and psychological struggles as a means of exploring our shared anxieties over pleasure, consumption, appearance, and health. As a woman who describes her own body as “wildly undisciplined,” Roxane understands the tension between desire and denial, between self-comfort and self-care. In Hunger, she explores her past—including the devastating act of violence that acted as a turning point in her young life—and brings readers along on her journey to understand and ultimately save herself.",
        bookPic: "21",
      },
      {
        bookTitle: "Too Big to Fail",
        bookAuthor: "Andrew Ross Sorkin",
        bookISBN: "9781846142383",
        bookPublish: "22-09-2009",
        bookRate: "4.1",
        bookQuote: "If a financial institution is too big to fail. It is too big to exist.",
        bookDescrip: "Too Big to Fail: The Inside Story of How Wall Street and Washington Fought to Save the Financial System—and Themselves, also known as Too Big to Fail: Inside the Battle to Save Wall Street, is a non-fiction book by Andrew Ross Sorkin chronicling the events of the 2008 financial crisis and the collapse of Lehman Brothers from the point of view of Wall Street CEOs and US government regulators.",
        bookPic: "20",
      },
      {
        bookTitle: "Vicious",
        bookAuthor: "V.E. Schwab",
        bookISBN: "9780765335340",
        bookPublish: "24-09-2013",
        bookRate: "4.2",
        bookQuote: "Plenty of humans were monstrous and plenty of monsters knew how to play at being human.",
        bookDescrip: "Vicious is a fantasy novel by American author V. E. Schwab published by Tor Books in 2013, focused around two college students who learn how to create superhuman abilities and later become archenemies.",
        bookPic: "22",
      },{
        bookTitle: "Six of Crows",
        bookAuthor: "Leigh Bardugo",
        bookISBN: "9781522609735",
        bookPublish: "29-09-2015",
        bookRate: "4.5",
        bookQuote: "The heart is an arrow. It demands aim to land true.",
        bookDescrip: "Ketterdam: a bustling hub of international trade where anything can be had for the right price - and no one knows that better than criminal prodigy, Kaz Brekker. Kaz is offered a chance at a deadly heist that could make him rich beyond his wildest dreams. But he can't pull it off alone. A convict with a thirst for revenge. A sharpshooter who can't walk away from a wager. A runaway with a privileged past. A spy known as the Wraith. A Heartrender using her magic to survive the slums. A thief with a gift for unlikely escapes. This is a fantasy epic about six dangerous outcasts and one impossible heist. Kaz's crew is the only thing that might stand between the world and destruction - if they don't kill each other first.",
        bookPic: "23",
      },{
        bookTitle: "Inferno",
        bookAuthor: "Dan Brown",
        bookISBN: "9780593072493",
        bookPublish: "14-05-2013",
        bookRate: "4.2",
        bookQuote: "The darkest places in hell are reserved for those who maintain their neutrality in times of moral crisis.",
        bookDescrip: "In the novel Inferno by Dan Brown, Harvard professor Robert Langdon is recruited by the World Health Organization (WHO) to help locate a deadly pathogen. The virus is believed to have been created by Bertrand Zobrist, a Transhumanist who thought that the world was in danger of collapse because of overpopulation.",
        bookPic: "24",
      },{
        bookTitle: "Halo: The Fall of Reach",
        bookAuthor: "Eric Nylund",
        bookISBN: "9781841494203",
        bookPublish: "30-10-2001",
        bookRate: "4.3",
        bookQuote: "I know we're losing...I want to know if we've lost.",
        bookDescrip: "As the bloody Human-Covenant War rages on Halo, the fate of humankind may rest with one warrior, the lone SPARTAN survivor of another legendary battle... the desperate, take-no-prisoners struggle that led humanity to Halo--the fall of the planet Reach. Now, brought to life for the first time, here is the full story of that glorious, doomed conflict.",
        bookPic: "25",
      },{
        bookTitle: "Angels and Demons",
        bookAuthor: "Dan Brown",
        bookISBN: "9780743486224",
        bookPublish: "01-05-2000",
        bookRate: "3.9",
        bookQuote: "Our minds sometimes see what our hearts wish were true.",
        bookDescrip: "An ancient secret brotherhood. A devastating new weapon of destruction. An unthinkable target. When world-renowned Harvard symbologist Robert Langdon is summoned to his first assignment to a Swiss research facility to analyze a mysterious symbol -- seared into the chest of a murdered physicist -- he discovers evidence of the unimaginable: the resurgence of an ancient secret brotherhood known as the Illuminati...the most powerful underground organization ever to walk the earth. The Illuminati has now surfaced to carry out the final phase of its legendary vendetta against its most hated enemy -- the Catholic Church.",
        bookPic: "26",
      },
      {
        bookTitle: "The Seven Husbands of Evelyn Hugo",
        bookAuthor: "Taylor-Jenkins Reid",
        bookISBN: "9781398515697",
        bookPublish: "13-06-2017",
        bookRate: "4.4",
        bookQuote: "People think that intimacy is about sex. But intimacy is about truth when you realize you can tell someone your truth, when you can show yourself to them, when you stand in front of them bare and their response is 'you're safe with me' - that's intimacy.",
        bookDescrip: "Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself. Why her? Why now? The Seven Husbands of Evelyn Hugo is a mesmerizing journey through the splendour of old Hollywood into the harsh realities of the present day as two women struggle with what it means and what it costs to face the truth.",
        bookPic: "27",
      },{
        bookTitle: "The Queen's Gambit",
        bookAuthor: "Walter Tevis",
        bookISBN: "9781474622578",
        bookPublish: "11-03-2003",
        bookRate: "4.2",
        bookQuote: "What is the object of playing a gambit opening...? To acquire a reputation of being a dashing player at the cost of losing game.",
        bookDescrip: "When she is sent to an orphanage at the age of eight, Beth Harmon soon discovers two ways to escape her surroundings, albeit fleetingly: playing chess and taking the little green pills given to her and the other children to keep them subdued. Before long, it becomes apparent that hers is a prodigious talent, and as she progresses to the top of the US chess rankings she is able to forge a new life for herself. But she can never quite overcome her urge to self-destruct. For Beth, there's more at stake than merely winning and losing.",
        bookPic: "28",
      },{
        bookTitle: "It Ends With Us",
        bookAuthor: "Colleen Hoover",
        bookISBN: "9781501110368",
        bookPublish: "02-08-2016",
        bookRate: "4.4",
        bookQuote: "Sometimes it's the one who loves you that hurts you the most.",
        bookDescrip: "Lily hasn't always had it easy, but that's never stopped her from working hard for the life she wants. She's come a long way from the small town in Maine where she grew up - she graduated from college, moved to Boston, and started her own business. So when she feels a spark with a gorgeous neurosurgeon named Ryle Kincaid, everything in Lily's life suddenly seems almost too good to be true.",
        bookPic: "29",
      },{
        bookTitle: "Sapiens: A Brief History of Humankind",
        bookAuthor: "Yuval Noah Harari",
        bookISBN: "9780099590088",
        bookPublish: "10-02-2015",
        bookRate: "4.4",
        bookQuote: "Culture tends to argue that it forbids only that which is unnatural. But from a biological perspective, nothing is unnatural. Whatever is possible is by definition also natural. A truly unnatural behaviour, one that goes against the laws of nature, simply cannot exist, so it would need no prohibition.",
        bookDescrip: "Yuval Noah Harari's book, 'Sapiens,' traces the origins, mechanisms, and effects of what we think of as “human progress” from small bands of hunter gatherers 100,000 years ago to the present-day global network through which our species has come to dominate the entire Earth. In this bold and provocative book, Yuval Noah Harari explores who we are, how we got here and where we're going.",
        bookPic: "30",
      },{
        bookTitle: "The Secret History",
        bookAuthor: "Donna Tartt",
        bookISBN: "9780140167771",
        bookPublish: "11-09-1992",
        bookRate: "4.1",
        bookQuote: "What we did was terrible, but still I don't think any of us were bad, exactly; chalk it up to weakness on my part, hubris on Henry's, too much Greek prose composition - whatever you like.",
        bookDescrip: "Under the influence of their charismatic classics professor, a group of clever, eccentric misfits at an elite New England college discover a way of thinking and living that is a world away from the humdrum existence of their contemporaries. But when they go beyond the boundaries of morality, their lives are changed profoundly and for ever. The Secret History is a story of two parts; the chain of events that led to the death of a classmate - and what happened next.",
        bookPic: "31",
      },{
        bookTitle: "All the Light We Cannot See",
        bookAuthor: "Anthony Doerr",
        bookISBN: "9780007548699",
        bookPublish: "06-05-2014",
        bookRate: "4.3",
        bookQuote: "Open your eyes and see what you can with them before they close forever.",
        bookDescrip: "A beautiful, stunningly ambitious novel about a blind French girl and a German boy whose paths collide in occupied France as both try to survive the devastation of World War II. In this magnificent, deeply moving novel, the stories of Marie-Laure and Werner illuminate the ways, against all odds, people try to be good to one another. Ten years in the writing, All the Light We Cannot See is Anthony Doerr's most ambitious and dazzling work",
        bookPic: "32",
      },
      {
        bookTitle: "The Book Thief",
        bookAuthor: "Markus Zusak",
        bookISBN: "9780307475732",
        bookPublish: "14-05-2006",
        bookRate: "4.4",
        bookQuote: "It amazes me what humans can do, even when streams are flowing down their faces and they stagger on, coughing and searching and finding.",
        bookDescrip: "It is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will be busier still. By her brother's graveside, Liesel's life is changed when she picks up a single object, partially hidden in the snow. It is The Gravedigger's Handbook, left behind there by accident, and it is her first act of book thievery. So begins a love affair with books and words, as Liesel, with the help of her accordian-playing foster father, learns to read. Soon she is stealing books from Nazi book-burnings, the mayor's wife's library, wherever there are books to be found. But these are dangerous times. When Liesel's foster family hides a Jew in their basement, Liesel's world is both opened up, and closed down. In superbly crafted writing that burns with intensity, award-winning author Markus Zusak has given us one of the most enduring stories of our time.",
        bookPic: "33",
      },
      {
        bookTitle: "Cutting for Stone",
        bookAuthor: "Abraham Verghese",
        bookISBN: "9780307271341",
        bookPublish: "03-02-2009",
        bookRate: "4.3",
        bookQuote: "Wasn't that the definition of home? Not where you are from, but where you are wanted.",
        bookDescrip: "A sweeping, emotionally riveting first novel - an enthralling family saga of Africa and America, doctors and patients, exile and home. An unforgettable journey into one man’s remarkable life, and an epic story about the power, intimacy, and curious beauty of the work of healing others.",
        bookPic: "34",
      }
    ],
  },
}
</script>
